version: '3.5'

services:
  idunn:
    deploy:
      placement:
        constraints:
          - node.labels.type != node1
          - node.labels.type != node4
    environment:
      - http_proxy=http://10.100.9.1:2001
      - https_proxy=http://10.100.9.1:2001
      - IDUNN_COMBIGO_API_KEY=${QMAPS_COMBIGO_API_KEY_PLIVE}
      - IDUNN_LOG_JSON=1
      - IDUNN_MIMIR_ES=http://es:9200
      - IDUNN_BRAGI_BASE_URL=http://geocoder-varnish/maps/geocoder
      - IDUNN_WIKI_API_REDIS_URL=idunn-redis:6379
      - IDUNN_WIKI_ES=http://wiki-es:9200
      - IDUNN_WIKI_USER_AGENT=Idunn/0.1.1 (https://www.qwant.com; https://www.qwant.com/maps)
      - IDUNN_THUMBR_SALT=${QMAPS_THUMBR_SECRET_PLIVE}
      - IDUNN_THUMBR_URLS=https://s1.qwant.plive/thumbr,https://s2.qwant.plive/thumbr
      - IDUNN_PJ_ES=http://wiki-es:9200
      - IDUNN_PJ_ES_QUERY_TEMPLATE=pagesjaunes_query
      - IDUNN_MAPBOX_DIRECTIONS_ACCESS_TOKEN=$QMAPS_MAPBOX_TOKEN_PLIVE
      - IDUNN_BLOCK_COVID_ENABLED=false
      - IDUNN_COVID19_BLOCK_COUNTRIES=FR,CH,ES,FI
      - IDUNN_NLU_TAGGER_URL=http://1701_nlu:9009/nlu
      - IDUNN_NLU_TAGGER_DOMAIN=MAPS
      - IDUNN_RECYCLING_SERVER_URL=https://api.datalake.pprod.finisteresmartconnect.fr # SDEF preprod
      - IDUNN_RECYCLING_SERVER_USERNAME=qwant
      - IDUNN_RECYCLING_SERVER_PASSWORD=${QMAPS_SDEF_PREPROD_PASSWORD}
      - IDUNN_SECRET=${QMAPS_SECRET_PLIVE}
      - IDUNN_BASE_URL=https://www.qwant.plive/maps/detail/
      - IDUNN_MAPS_BASE_URL=https://www.qwant.plive/maps/
      - IDUNN_PJ_API_ID=${QMAPS_PJ_ID_PLIVE}
      - IDUNN_PJ_API_SECRET=${QMAPS_PJ_SECRET_PLIVE}
      - IDUNN_BANCHECK_ENABLED=true
      - IDUNN_BANCHECK_TIMEOUT=0.5
      - IDUNN_QWANT_API_BASE_URL=http://foundation
      - IDUNN_IA_SUCCESS_ON_GENERIC_QUERIES=true
      - IDUNN_DIRECTIONS_RL_MAX_REQUESTS=20
      - IDUNN_DIRECTIONS_RL_EXPIRE=180 # per 3 minutes
      - no_proxy=es,bragi,wiki-es,geocoder-varnish,1701_nlu,foundation
    extra_hosts:
      - "wiki-es:10.100.33.34"
      - "geocoder-varnish:10.104.1.7"
      - "foundation:10.108.3.44"
    networks:
      - product-maps-prelive_default


networks:
  product-maps-prelive_default:
    external: true
